SECONDS = 1
HOUR = 60 * SECONDS
DSA_TIMEOUT = 10 * SECONDS

HOST = '127.0.0.1'
TEMP_STORAGE_PORT = '8001'

# adjusted difficulty
MINE_RATE = 4 * SECONDS

DIFFICULTY = 16

STARTING_BALANCE = 1000

MINING_REWARD = 1
MINING_REWARD_INPUT = {'address': '*--mining-reward--*'}
