NANOSECONDS = 1
MICROSECONDS = 1000 * NANOSECONDS
MILLISECONDS = 1000 * MICROSECONDS
SECONDS = 1000 * MILLISECONDS

HOST = '127.0.0.1'
TEMP_STORAGE_PORT = '8001'

# adjusted difficulty
MINE_RATE = 4 * SECONDS

DIFFICULTY = 20

STARTING_BALANCE = 1000

MINING_REWARD = 1
MINING_REWARD_INPUT = {'address': '*--mining-reward--*'}
